use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkCounters {
    pub rhs_calls: u64,
    pub rhs_batch_calls: u64,
    pub rhs_evaluations: u64,
    pub ft_calls: u64,
    pub jacobian_builds: u64,
    pub jvp_calls: u64,
    pub jvp_vectors: u64,
    pub mass_matvecs: u64,
    pub nonlinear_solves: u64,
    pub nonlinear_iterations: u64,
    pub nonlinear_residual_evaluations: u64,
    pub nonlinear_jacobian_evaluations: u64,
    pub nonlinear_failures: u64,
    pub linear_solves: u64,
    pub linear_iterations: u64,
    pub linear_matvecs: u64,
    pub preconditioner_apps: u64,
    pub direct_factorizations: u64,
    pub direct_solve_calls: u64,
    pub recycle_projection_calls: u64,
    pub recycle_same_operator_uses: u64,
    pub recycle_cross_operator_refreshes: u64,
    pub recycle_refresh_matvecs: u64,
    pub recycle_updates: u64,
    pub recycle_vectors_selected: u64,
    pub recycle_dropped_vectors: u64,
    pub harmonic_ritz_solves: u64,
    pub orthogonalization_inner_products: u64,
    pub orthogonalization_vector_updates: u64,
    pub diagnostic_matvecs: u64,
    pub phi_actions: u64,
    pub phi_krylov_vectors: u64,
    pub phi_projected_exponentials: u64,
    pub phi_restarts: u64,
    pub phi_dense_oracle_calls: u64,
    pub block_linear_solves: u64,
    pub block_linear_iterations: u64,
    pub block_matvecs: u64,
    pub block_preconditioner_apps: u64,
    pub fast_attempts: u64,
    pub fast_accepts: u64,
    pub fallback_steps: u64,
    pub accepted_steps: u64,
    pub rejected_steps: u64,
}

impl WorkCounters {
    /// Saturating component-wise accumulation for independently measured work ledgers.
    ///
    /// This is used when bounded parallel stage/RHS jobs keep local counters and merge them
    /// only after every job has completed.  Saturation preserves the existing failure-safe
    /// accounting semantics instead of wrapping on pathological runs.
    pub fn accumulate(&mut self, other: Self) {
        macro_rules! add_fields { ($($f:ident),* $(,)?) => { $(self.$f = self.$f.saturating_add(other.$f);)* } }
        add_fields!(
            rhs_calls,
            rhs_batch_calls,
            rhs_evaluations,
            ft_calls,
            jacobian_builds,
            jvp_calls,
            jvp_vectors,
            mass_matvecs,
            nonlinear_solves,
            nonlinear_iterations,
            nonlinear_residual_evaluations,
            nonlinear_jacobian_evaluations,
            nonlinear_failures,
            linear_solves,
            linear_iterations,
            linear_matvecs,
            preconditioner_apps,
            direct_factorizations,
            direct_solve_calls,
            recycle_projection_calls,
            recycle_same_operator_uses,
            recycle_cross_operator_refreshes,
            recycle_refresh_matvecs,
            recycle_updates,
            recycle_vectors_selected,
            recycle_dropped_vectors,
            harmonic_ritz_solves,
            orthogonalization_inner_products,
            orthogonalization_vector_updates,
            diagnostic_matvecs,
            phi_actions,
            phi_krylov_vectors,
            phi_projected_exponentials,
            phi_restarts,
            phi_dense_oracle_calls,
            block_linear_solves,
            block_linear_iterations,
            block_matvecs,
            block_preconditioner_apps,
            fast_attempts,
            fast_accepts,
            fallback_steps,
            accepted_steps,
            rejected_steps,
        );
    }

    pub fn delta(self, before: Self) -> Self {
        macro_rules! sub_fields { ($($f:ident),* $(,)?) => { Self { $($f: self.$f.saturating_sub(before.$f),)* } }; }
        sub_fields!(
            rhs_calls,
            rhs_batch_calls,
            rhs_evaluations,
            ft_calls,
            jacobian_builds,
            jvp_calls,
            jvp_vectors,
            mass_matvecs,
            nonlinear_solves,
            nonlinear_iterations,
            nonlinear_residual_evaluations,
            nonlinear_jacobian_evaluations,
            nonlinear_failures,
            linear_solves,
            linear_iterations,
            linear_matvecs,
            preconditioner_apps,
            direct_factorizations,
            direct_solve_calls,
            recycle_projection_calls,
            recycle_same_operator_uses,
            recycle_cross_operator_refreshes,
            recycle_refresh_matvecs,
            recycle_updates,
            recycle_vectors_selected,
            recycle_dropped_vectors,
            harmonic_ritz_solves,
            orthogonalization_inner_products,
            orthogonalization_vector_updates,
            diagnostic_matvecs,
            phi_actions,
            phi_krylov_vectors,
            phi_projected_exponentials,
            phi_restarts,
            phi_dense_oracle_calls,
            block_linear_solves,
            block_linear_iterations,
            block_matvecs,
            block_preconditioner_apps,
            fast_attempts,
            fast_accepts,
            fallback_steps,
            accepted_steps,
            rejected_steps,
        )
    }
}
