from pathlib import Path
import collections,hashlib,json,datetime
p=Path(__file__).resolve().parent;d=json.loads((p/'native/suite_summary.json').read_text());plan=json.loads((p/'FROZEN_PLAN.json').read_text())
assert d.get('finished_utc'),'Native campaign has not finalized'
checks=[];coverage=[]
for b in d['binaries']:
 if b['status']=='PASS':
  assert b['summary_consistent'] and b['invocation']['exit_code']==0 and not b['invocation']['timed_out'],b['target']
  text=(p/'native'/b['invocation']['stdout']).read_text()
  assert 'test result: ok.' in text,b['target']
 for t in b['tests']:coverage.append({'target':b['target'],'test':t['name'],'status':t['status'],'stdout':('native/'+b['invocation']['stdout']) if 'invocation' in b else None})
counts=dict(collections.Counter(x['status'] for x in coverage));assert counts==d['test_counts'];assert d['source_unchanged'];assert d['build']['exit_code']==0 and d['build_finished_records'][-1]['success'];assert len(d['binaries'])>0 and len(coverage)>0
changed=[b for b in d['binaries'] if b['target'] in plan['changed_priority_targets']];assert len(changed)==len(plan['changed_priority_targets'])
receipt={'schema':'vigilode.r4.runtime_final.v1','recorded_utc':datetime.datetime.now(datetime.UTC).isoformat(),'audited_source_commit':d['audited_source_commit'],'execution_commit':d['execution_commit'],'prereg_commit':d['prereg_commit'],'build_status':'PASS','build_elapsed_seconds':d['build']['elapsed_seconds'],'native_campaign_status':d['full_suite_claim'],'inventory':{'binary_count':len(d['binaries']),'named_test_count':len(coverage)},'test_counts':counts,'binary_counts':d['binary_counts'],'changed_targets':{'target_count':len(changed),'all_harnesses_exit_zero_and_summary_consistent':all(b['status']=='PASS' for b in changed),'test_counts':dict(collections.Counter(t['status'] for b in changed for t in b['tests']))},'source_tracked_crates_cargo_toolchain_unchanged':d['source_unchanged'],'complete_workspace_pass':d['full_suite_claim'].startswith('PASS_WITH'),'doctests':'NOT_RUN','performance_claim':'NOT_EVALUATED','ignored_tests':'NOT_RUN','timeouts':'Audit budget termination, not assertion failure; exit_code 124 is runner timeout sentinel.','failure_classification':'No assertion failure observed' if not counts.get('FAIL',0) else 'See failed native tests','native_summary':'native/suite_summary.json','named_test_coverage':'TEST_COVERAGE.json','runtime_incidents':'runtime_incidents.json','selected_readback':'Finalizer checks each PASS harness raw summary, return status, per-test count agreement; not a second scientific execution.'}
(p/'TEST_COVERAGE.json').write_text(json.dumps({'schema':'vigilode.r4.named_test_coverage.v1','tests':coverage},indent=2)+'\n');(p/'FINAL_RUNTIME_SUMMARY.json').write_text(json.dumps(receipt,indent=2)+'\n')
missing=[b for b in d['binaries'] if b['status']!='PASS'];lines=['# R4 Rust 실행 결과','',f"전체 workspace/all-targets/all-features debug 빌드는 실제 exit 0, {d['build']['elapsed_seconds']:.2f}초에 완료했다. Cargo `build-finished: success`와 {len(d['binaries'])}개 native harness를 확인했다. 검사 대상 source는 `{d['audited_source_commit']}`, 사전등록 commit은 `{d['prereg_commit']}`다.",'',f"실행한 범위의 집계: `{json.dumps(counts,ensure_ascii=False)}`. 전체 native inventory는 {len(coverage)}개 named test다. 전체 suite 판정은 `{d['full_suite_claim']}`이며 doctest와 ignored test는 실행하지 않았다.",'',f"직접 변경된 15개 harness는 전부 정상 종료했다. {receipt['changed_targets']['test_counts'].get('PASS',0)}개 test가 통과했고 {receipt['changed_targets']['test_counts'].get('IGNORED_NOT_RUN',0)}개 ignored test는 실행하지 않았다. 이 결과는 기존 test 계약을 만족한다는 구현 검증이며 별도 적대적 반례나 이론적 주장을 대체하지 않는다.",'','고정 실행 예산은 build 600초, native 전체 300초, 일반 harness 30초, 역사적 긴 harness 60초다. timeout은 수치 결과 실패나 assertion failure로 재분류하지 않는다. budget 종료로 실행하지 못한 test도 named inventory와 함께 보존했다. 실제 속도·scaling·production 성능은 측정하지 않았다.','', '## 완료되지 않은 harness','', '| Target | 상태 |','|---|---|']
lines += [f"| `{b['target']}` | {b['status']} |" for b in missing]
lines += ['','## 실행환경과 재현 범위','','Rust 1.94.1, `--locked --offline`, registry dependency 118개 exact version/package checksum 일치, workspace metadata 총 123개 package. cgroup RAM 8 GiB/CPU quota 8, build jobs 1, native test threads 1, incremental off, dev/test codegen units 1이다. 모든 Cargo build는 공유 flock으로 직렬화했다. 사전등록 후 실행했고 native 실행은 source 또는 Cargo dependency lock을 바꾸지 않았다.','','최초 vendor ownership 복원 실패와 target-dir 상대경로 해석 오류는 `runtime_incidents.json` 및 setup receipt에 분리 기록했다. 원 registered runner는 사전등록 commit bytes와 동일하다. 안정적인 shared target symlink를 통해 native artifact를 공유했으며, 정규화된 별도 helper는 실행하지 않았다.','','`FINAL_RUNTIME_SUMMARY.json`은 최종 집계, `TEST_COVERAGE.json`은 모든 test의 상태, `native/suite_summary.json`과 대응 stdout/stderr는 원 실행 증거다.']
(p/'RUNTIME_RESULTS_KO.md').write_text('\n'.join(lines)+'\n');print(json.dumps(receipt,indent=2))
