use rodas5p_core::{DenseMatrix, DenseOperator,WorkCounters,weight_phi_vectors,binary_split,binary_scale,dense_fused_phi_action,dense_fused_phi_action_report};
use rodas5p_core::polynomial_action::{PolynomialBasis,SymmetricNonpositiveOperator,JointPhiInput,CoefficientCache,joint_phi_action,joint_phi_action_unbounded};
use rodas5p_core::transform_bound::{ExpBound,TransformBound,bound_transform_error};
use rodas5p_core::directed::{mul_up,add_up,sqrt_up};
use rodas5p_integrators::{fused_phi_action,fused_phi_action_incremental,FusedPhiKrylovConfig};
use serde_json::{Value,json};
use std::sync::Arc;
fn emit(v: Value){println!("{}",v);}
fn bits(v: &[f64])->Vec<String>{v.iter().map(|x|format!("{:016x}",x.to_bits())).collect()}
fn dm(rows:&[Vec<f64>])->DenseMatrix{DenseMatrix::from_rows(&rows.iter().map(Vec::as_slice).collect::<Vec<_>>()).unwrap()}
fn boundrow(id:&str,a:&DenseMatrix,h:f64,b:&[Vec<f64>],s:&[Vec<f64>]){
 let r=bound_transform_error(a,h,b,s); match r{Ok(v)=>{let up=match &v{TransformBound::Bounded{upper,..}=>Some(upper.to_f64_up()),_=>None};emit(json!({"kind":"transform","id":id,"h_bits":bits(&[h]),"a_bits":a.as_slice().iter().map(|x|format!("{:016x}",x.to_bits())).collect::<Vec<_>>(),"b_bits":b.iter().map(|x|bits(x)).collect::<Vec<_>>(),"stored_bits":s.iter().map(|x|bits(x)).collect::<Vec<_>>(),"result":v,"f64_up":up,"admits_zero":v.admits(0.),"admits_negative":v.admits(-10.)}));},Err(e)=>emit(json!({"kind":"transform","id":id,"error":e.to_string()}))}
}
fn safe_norm(v:&[f64])->Result<ExpBound,String>{
 if v.iter().any(|x|!x.is_finite()){return Err("nonfinite".into())}
 let max=v.iter().copied().map(f64::abs).fold(0.0,f64::max); if max==0. {return Ok(ExpBound::ZERO)}
 let (_,e)=binary_split(max); let mut sum=0.;
 for &x in v {let ax=x.abs();let y=binary_scale(ax,-e);let y=if ax!=0.&&binary_scale(y,e)!=ax {y.next_up()}else{y};sum=add_up(sum,mul_up(y,y).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;}
 let mut r=ExpBound::exact(sqrt_up(sum).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;r.exponent+=e;Ok(r)
}
fn inverse_factorial(k:usize)->ExpBound{let mut v=ExpBound::exact(1.).unwrap();for j in 1..=k{v=v.div_integer(j as f64).unwrap();}v}
fn main(){
 let a=dm(&[vec![0.,1e308],vec![0.,0.]]);let b=vec![vec![1e-300,0.],vec![0.,0.],vec![0.,1e-310]];
 for h in [1e-8,-1e-8]{let(stored,lost)=weight_phi_vectors(h,&b).unwrap();boundrow(&format!("original_{h}"),&a,h,&b,&stored);let op=Arc::new(DenseOperator::new(a.clone()).unwrap());let cfg=FusedPhiKrylovConfig{relative_tolerance:1e-12,absolute_tolerance:0.,maximum_substeps:1,..Default::default()};let mut work=WorkCounters::default();for prefix in [false,true]{let out=if prefix{fused_phi_action_incremental(op.clone(),h,&b,cfg.clone(),&mut work)}else{fused_phi_action(op.clone(),h,&b,cfg.clone(),&mut work)};emit(match out{Ok(r)=>json!({"kind":"closure","h":h,"prefix":prefix,"converged":r.converged,"status":r.transform_status,"lost":lost}),Err(e)=>json!({"kind":"closure","error":e.to_string()})});}emit(json!({"kind":"dense_closure","h":h,"typed_error":dense_fused_phi_action(&a,h,&b).unwrap_err().to_string(),"authoritative":dense_fused_phi_action_report(&a,h,&b).unwrap().is_reference_authoritative()}));}
 let small_nilpotent=dm(&[vec![0.,0.25],vec![0.,0.]]); let small_b=vec![vec![0.,0.],vec![0.,0.],vec![0.,1.]]; let(small_s,_)=weight_phi_vectors(1000.1,&small_b).unwrap(); boundrow("subunit_nilpotent_generated",&small_nilpotent,1000.1,&small_b,&small_s);
 let zero=dm(&[vec![0.]]);boundrow("signed_stored_order0",&zero,1.,&[vec![1.]],&[vec![-1.]]);boundrow("negative_tolerance",&zero,1.,&[vec![1.]],&[vec![0.]]);
 for p in [4,30,50,170,171,172]{let mut b=vec![vec![0.];p+1];b[p][0]=1.;let(s,_)=weight_phi_vectors(1.1,&b).unwrap();boundrow(&format!("order_{p}"),&zero,1.1,&b,&s);if let TransformBound::Bounded{delta,..}=bound_transform_error(&zero,1.1,&b,&s).unwrap(){let coefficient=inverse_factorial(p);emit(json!({"kind":"factorial_candidate","order":p,"coefficient":coefficient,"error_bound":coefficient.mul(delta[p]).unwrap()}));}}
 let matrices=vec![("zero",vec![vec![0.,0.],vec![0.,0.]],0.,0.),("scalar",vec![vec![-2.,0.],vec![0.,-2.]],2.,2.),("diag",vec![vec![-1.,0.],vec![0.,-2.]],1.,2.),("sym",vec![vec![-2.,1.],vec![1.,-2.]],1.,3.)];
 for(name,rows,lambda,rho)in matrices{let op=SymmetricNonpositiveOperator::new(dm(&rows),lambda,rho,"exact-domain").unwrap();for h in [0.,1e-12,0.1,1.,10.]{for basis in [PolynomialBasis::Chebyshev,PolynomialBasis::Laguerre]{let w=[vec![1.,-1.],vec![-1.,0.5],vec![0.125,-0.25],vec![-0.25,0.125],vec![0.125,-0.125]];let mut work=WorkCounters::default();let r=joint_phi_action(&op,h,JointPhiInput::Distinct(&w),basis,1e-12,None,&mut work);emit(match r{Ok(report)=>json!({"kind":"polynomial","id":format!("{name}_{h}_{basis:?}"),"matrix":rows,"matrix_bits":rows.iter().map(|x|bits(x)).collect::<Vec<_>>(),"h_bits":bits(&[h]),"w_bits":w.iter().map(|x|bits(x)).collect::<Vec<_>>(),"report":report,"work":work}),Err(e)=>json!({"kind":"polynomial","id":format!("{name}_{h}_{basis:?}"),"error":e.to_string()})});}}}
 let op=SymmetricNonpositiveOperator::new(dm(&[vec![-1.,0.],vec![0.,-2.]]),1.,2.,"diag").unwrap();let vector=[1.,-0.5];let scales=[1.,-1.,0.5,-0.25,0.125];let mut cache=CoefficientCache::default();for(h,budget)in [(0.1,1e-12),(0.1,1e-12),(1.,1e-12),(0.1,1e-30)]{let mut work=WorkCounters::default();let r=joint_phi_action(&op,h,JointPhiInput::SameVector{vector:&vector,scales},PolynomialBasis::Chebyshev,budget,Some(&mut cache),&mut work);emit(json!({"kind":"same_cache","h":h,"budget":budget,"cache_len":cache.len(),"report":r.ok(),"work":work}));}
 for amplitude in [1e-300,1e300]{let w=[vec![amplitude,0.],vec![0.,amplitude],vec![0.,0.],vec![0.,0.],vec![0.,0.]];let mut work=WorkCounters::default();let r=joint_phi_action(&op,0.1,JointPhiInput::Distinct(&w),PolynomialBasis::Chebyshev,amplitude.abs()*1e-12,None,&mut work);emit(match r{Ok(report)=>json!({"kind":"range","amplitude":amplitude,"report":report}),Err(e)=>json!({"kind":"range","amplitude":amplitude,"error":e.to_string()})});}
 for (name,rows,lambda,rho) in [("nonnormal",vec![vec![-1.,1.],vec![0.,-2.]],1.,2.),("bad_spectrum",vec![vec![-1.,2.],vec![2.,-1.]],0.,1.),("degenerate_lie",vec![vec![-1.,1.],vec![1.,-1.]],1.,1.)]{let r=SymmetricNonpositiveOperator::new(dm(&rows),lambda,rho,"unverified-test");match r{Err(e)=>emit(json!({"kind":"domain","id":name,"error":e.to_string()})),Ok(op)=>{let w=[vec![1.,0.],vec![0.,0.],vec![0.,0.],vec![0.,0.],vec![0.,0.]];let mut work=WorkCounters::default();emit(match joint_phi_action(&op,0.1,JointPhiInput::Distinct(&w),PolynomialBasis::Chebyshev,1e-12,None,&mut work){Ok(report)=>json!({"kind":"domain","id":name,"report":report}),Err(e)=>json!({"kind":"domain","id":name,"error":e.to_string()})});}}}
 for v in [vec![1e300,1e300],vec![1e-300,1e-300],vec![f64::from_bits(1),f64::from_bits(1)],vec![1.,f64::from_bits(1)],vec![0.,0.]]{let result=safe_norm(&v);emit(json!({"kind":"norm_candidate","input_bits":bits(&v),"bound":result.unwrap()}));}
 let w=[vec![1.,0.],vec![0.,1.],vec![0.,0.],vec![0.,0.],vec![0.,0.]];let mut wa=WorkCounters::default();let mut wb=WorkCounters::default();let a=joint_phi_action(&op,0.1,JointPhiInput::Distinct(&w),PolynomialBasis::Chebyshev,1e-12,None,&mut wa).unwrap();let b=joint_phi_action_unbounded(&op,0.1,JointPhiInput::Distinct(&w),PolynomialBasis::Chebyshev,1e-12,None,&mut wb).unwrap();emit(json!({"kind":"unbounded","same_bits":bits(&a.fused)==bits(&b.fused),"status":b.total_error}));
}
