#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
VALIDATOR="$SCRIPT_DIR/validate-cargo-vendor.py"
VENDOR_DIR="${VIGILODE_CARGO_VENDOR_DIR:-}"

usage() {
  cat <<'EOF'
Usage:
  bash ./tools/cargo-offline.sh [--vendor-dir PATH] CARGO_SUBCOMMAND [ARGS...]

The vendor directory must be a standard Cargo directory source generated by
`cargo vendor`. It may also be supplied through VIGILODE_CARGO_VENDOR_DIR.
EOF
}

while (($#)); do
  case "$1" in
    --vendor-dir)
      if (($# < 2)); then
        printf 'ERROR: --vendor-dir requires a path\n' >&2
        exit 2
      fi
      VENDOR_DIR="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      break
      ;;
  esac
done

if [[ -z "$VENDOR_DIR" ]]; then
  printf '%s\n' \
    'ERROR: provide --vendor-dir PATH or set VIGILODE_CARGO_VENDOR_DIR' >&2
  exit 2
fi
if (($# == 0)); then
  printf 'ERROR: no Cargo subcommand supplied\n' >&2
  usage >&2
  exit 2
fi
if [[ ! -d "$VENDOR_DIR" ]]; then
  printf 'ERROR: Cargo vendor directory does not exist: %s\n' "$VENDOR_DIR" >&2
  exit 2
fi

VENDOR_DIR="$(cd -- "$VENDOR_DIR" && pwd -P)"
python3 "$VALIDATOR" "$VENDOR_DIR" >/dev/null

if command -v cargo >/dev/null 2>&1; then
  CARGO_BIN="$(command -v cargo)"
else
  printf 'ERROR: cargo is not available on PATH\n' >&2
  exit 127
fi

TMP_CARGO_HOME="$(mktemp -d "${TMPDIR:-/tmp}/vigilode-cargo-offline.XXXXXX")"
cleanup() {
  rm -rf -- "$TMP_CARGO_HOME"
}
trap cleanup EXIT INT TERM

mkdir -p "$TMP_CARGO_HOME"
cat > "$TMP_CARGO_HOME/config.toml" <<EOF
[source.crates-io]
replace-with = "vigilode-vendored-sources"

[source.vigilode-vendored-sources]
directory = "${VENDOR_DIR}"

[net]
offline = true
EOF

cd -- "$REPO_ROOT"
CARGO_HOME="$TMP_CARGO_HOME" "$CARGO_BIN" "$@"
