from pathlib import Path
import json,hashlib,datetime
p=Path(__file__).resolve().parent
r=json.loads((p/'results.json').read_text())
claims=[
 {'id':'R3-HOM-01','title':'Quadratic componentwise outward stage and observable enclosure','status':['derived','numerically checked','implementation-verified'],'scope':'Explicit strict-lower projection of native rounded RODAS5P tableau; h>0, M=I, dimension1/2, quadratic remainder, exact rational inverse witness; fixed candidate WRMS scale','evidence':['certified_majorant.py','results.json','EXECUTION_RECEIPT.json'],'results':{'candidate_rows':24,'all_exact_checks':True,'primitive_exact_checks':162,'output_budget_01_accepts':12,'combined_proxy_1_accepts':8},'excluded':['unprojected native full-block target','exact native sequential arithmetic parity','general nonlinear callbacks','ODE truncation or global error','large matrix-free inverse witness','performance'],'production_decision':'HOLD'},
 {'id':'R3-HOM-02','title':'Finite path-sum doubling certificate with a priori state radius','status':['derived','numerically checked','implementation-verified'],'scope':'Strict-lower 8-stage block H, preset D=1e-4 independent of exact root; H^8=0; upward arithmetic; explicit radius closure','equation':'E=(I+H)(I+H^2)(I+H^4)a; require |alpha|E<=D','results':{'algebraic_doubling_levels':3,'dense_matrix_multiplications':5,'radius_closures':22,'explicit_rejects':2,'false_enclosures_among_closures':0,'actual_parallel_execution':False},'evidence':['certified_majorant.py','results.json'],'excluded':['wall-clock speedup','cheap dense U construction','native unprojected nilpotency'],'production_decision':'HOLD'},
 {'id':'R3-HOM-03','title':'Native transformed coefficient strict-lower premise fails bitwise','status':['implementation-verified','numerically checked'],'scope':'Native load_rodas5p_coefficients() exported binary64 bit patterns interpreted as exact real entries','classification':'CERTIFICATION_PREMISE_LIMITATION','severity':None,'results':{'alpha_upper_diagonal_nonzero':28,'alpha_max_abs_leakage':5.577737968635803e-16,'l_upper_diagonal_nonzero':34,'l_max_abs_leakage':3.7683229960916457e-16,'native_alpha_eighth_power_exact_zero':False,'native_l_eighth_power_exact_zero':False,'initial_native_probe_exit':1},'evidence':['native_tableau_bits.json','coefficient_structure.py','coefficient_structure.json','first_failure.json','first_run.stderr'],'excluded':['demonstrated macroscopic solver inaccuracy','new false native acceptance','silent projection repair'],'production_decision':'HOLD'},
 {'id':'R3-HOM-04','title':'q2 diagnostic replacement development path and complete cost condition','status':['derived'],'scope':'Source q2 state created at seventh W batch; eighth q=0 diagnostic does not modify state. Replacing its gate needs a valid output/embedded certificate for identical native target. Ideal equal-cost common-W model, >=8 workers','equation_with_diagnostic':'T/tW=8-2*p1+8*pf+c1+(1-p1)*c2+a+r','equation_diagnostic_replaced':'T/tW=7-p1+8*pf+c1+(1-p1)*c2+a+r','evidence':['HOMOTOPY_RESEARCH_KO.md','../evidence/source/SOURCE_MANIFEST.json'],'source_locations':[{'path':'crates/rodas5p-integrators/src/transactional_q1_q2.rs','lines':'658-708'}],'excluded':['measured speedup','authorized immediate production diagnostic removal'],'production_decision':'HOLD'}]
out={'schema':'vigilode.r3.homotopy.claims.v1','source_commit':r['source_commit'],'research_decision':'BOUNDED_RESULTS_READY_FOR_INDEPENDENT_REVIEW','production_decision':'HOLD','claims':claims,'findings_confirmed_new':[],'limitations':['Native full-block structural roundoff leakage remains outside projected-target certificate.','The exact inverse witness is specialized to dimensions 1/2.','Python doubling implementation is serial dense arithmetic.','Production gate and native target parity are not implemented.'],'prior_R2_advances':['actual outward arithmetic rather than nondirected tolerance check','exact inverse witness','output projection rounding and embedded projection covered','fixed-candidate WRMS bound','three-level majorant doubling with closure gate'],'first_failure_preserved':True}
(p/'CLAIMS.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
nodes=[
 {'id':'HOM-01','priority':'P1','title':'Define and enforce the stage target coefficient semantics','depends_on':[],'inputs':['native_tableau_bits.json','coefficient_structure.json'],'target_files':['crates/rodas5p-core/src/coefficients.rs','crates/rodas5p-integrators/src/block.rs','crates/rodas5p-integrators/src/sequential.rs'],'implementation':'Choose canonical strict-lower construction with validated Gamma inverse transformation, or retain full native coefficients and include their leakage in a verified target enclosure. Explicitly bind alpha+Gamma versus rounded L semantics. Do not silently zero coefficients inside certificate only.','acceptance':['Record native coefficient bits and target identifier.','Prove mathematical equality or quantified data-perturbation allowance between sequential and full-block consumers.','Any proof invoking H^8=0 checks exact structural zeros in its own target.'],'failure_status':'TARGET_SEMANTICS_UNRESOLVED','deliverables':['target_semantics.json','coefficient_structural_contracts.rs']},
 {'id':'HOM-02','priority':'P1','title':'Implement Rust outward certificate reference for small targets','depends_on':['HOM-01'],'inputs':['certified_majorant.py','results.json'],'target_files':['new research-only interval certificate module','new targeted Rust contracts'],'implementation':'Add residual enclosure, verified inverse witness interface, positive outward recurrence, output/embedded projection rounding and fixed candidate scale. Use exact oracle fixtures for arithmetic edge cases.','acceptance':['All24 recorded bounded fixtures enclosed on matching target.','underflow/cancellation/overflow handled with explicit fail-closed semantics.','Certification kind distinguishes stage-target bound from ODE error estimator.'],'failure_status':'CERTIFICATE_NOT_VALIDATED','deliverables':['rust_certificate_probe','native_certificate_results.json']},
 {'id':'HOM-03','priority':'P2','title':'Construct scalable structure-preserving inverse witness','depends_on':['HOM-01'],'inputs':['HOMOTOPY_RESEARCH_KO.md'],'target_files':['operator/preconditioner witness interface'],'implementation':'Start diagonal/block-triangular/banded W. For a general approximate inverse V verify |I-VW|<=R and a suitable comparison inverse, without assuming JVP access implies entrywise absolute bounds.','acceptance':['Matrix/operator identity ties witness to h,J,preconditioner and tolerances.','All inverse residual arithmetic enclosed.','Witness work/storage and rebuild/reuse cost recorded.'],'failure_status':'INVERSE_WITNESS_UNAVAILABLE','deliverables':['inverse_witness_contract','structured_fixture_results']},
 {'id':'HOM-04','priority':'P2','title':'Run block structured three-level certificate and radius predictor','depends_on':['HOM-02','HOM-03'],'inputs':['results.json'],'target_files':['parallel certificate experimental module'],'implementation':'Predict D from authorized past step data, assemble comparison H, evaluate finite path sum with block operations, then validate radius closure and output budgets. Keep all failed predictors in ledger.','acceptance':['No exact root/candidate reference leakage into D prediction.','All closure failures reject or fallback.','Independently compare enclosures with exact/small interval oracle.','Measure serial and actual worker execution including certificate work.'],'failure_status':'RADIUS_CLOSURE_OR_COST_FAIL','deliverables':['radius_predictor_contract','parallel_certificate_receipts']},
 {'id':'HOM-05','priority':'P2','title':'Replace q2 eighth diagnostic only after equivalent admission','depends_on':['HOM-02','HOM-03'],'inputs':['current transactional_q1_q2.rs'],'target_files':['crates/rodas5p-integrators/src/transactional_q1_q2.rs'],'implementation':'Keep the seventh-batch q2 candidate exactly fixed. Substitute rigorous native-target output/embedded admission for q=0 diagnostic, then remove only that unapplied diagnostic batch.','acceptance':['Candidate output/stages bit identity before/after diagnostic removal.','Wrong or unverified certificate cannot fast-accept.','W batch7 and certificate work separately accounted; fallback transaction preserved.'],'failure_status':'ADMISSION_EQUIVALENCE_NOT_ESTABLISHED','deliverables':['q2_diagnostic_replacement_contracts','work_ledger_comparison.json']},
 {'id':'HOM-06','priority':'P2','title':'Measure matched-accuracy full-attempt speedup','depends_on':['HOM-04','HOM-05'],'inputs':['source-bound timing/session protocol','full-attempt work records'],'target_files':['fair-ab campaign runner'],'implementation':'Compare serial baseline versus P=1,2,4,8 at equal output grid and tolerance. Include witness construction, RHS/JVP, certificate, rejected attempts and fallback in independent-session paired timings.','acceptance':['Same correctness/accuracy gate for all lanes.','No synthetic clock promoted as speed measurement.','Report p1,pf,certificate fraction,vector work,memory and total wall time.','Fail if significant work-accuracy regression or admission mismatch.'],'failure_status':'SPEEDUP_UNPROVEN','deliverables':['matched_accuracy_campaign.json','paired_timing_report']}
]
(p/'NEXT_STEPS.json').write_text(json.dumps({'schema':'vigilode.r3.homotopy.next.v1','source_commit':r['source_commit'],'nodes':nodes},ensure_ascii=False,indent=2)+'\n')
(p/'LITERATURE_SCOPE.json').write_text(json.dumps({'schema':'vigilode.r3.homotopy.literature.v1','sources':[{'title':'Verification methods: rigorous results using floating-point arithmetic','author':'Siegfried M. Rump','publication':'Acta Numerica (2010), pp287-449','url':'https://www.tuhh.de/ti3/rump/intlab/ActaNumerica2010.pdf','read_scope':'Introductory design principles and selected section10.3-10.4/equation10.9, not full163pages','supports':'verified residual/inverse-bound design methodology','does_not_establish':'RODAS-specific majorant, q1/q2 acceleration or prototype correctness'},{'provider':'SciSpace','read_scope':'search abstracts and bibliographic metadata','query':'Which verified numerical methods provide componentwise inverse bounds and rigorous residual error enclosures for linear systems while accounting for floating point rounding errors, especially Siegfried Rump Verification methods rigorous results using floating point arithmetic?','observation':'Same-title ISSAC2010 talk DOI10.1145/1837934.1837937 is distinct from the Acta Numerica review; not used as review DOI.'}]},indent=2)+'\n')
# Source evidence is immutable tracked source, not a science gate.
repo=p.parent.parent/'vigilode'
sourcefiles=['fixtures/rodas5p_coefficients_snapshot.json','crates/rodas5p-core/src/coefficients.rs','crates/rodas5p-core/src/matrix.rs','crates/rodas5p-integrators/src/block.rs','crates/rodas5p-integrators/src/sequential.rs','crates/rodas5p-integrators/src/homotopy.rs','crates/rodas5p-integrators/src/transactional_q1_q2.rs']
(p/'SOURCE_FILES.json').write_text(json.dumps({'source_commit':r['source_commit'],'files':[{'path':x,'sha256':hashlib.sha256((repo/x).read_bytes()).hexdigest()} for x in sourcefiles]},indent=2)+'\n')
receipt=json.loads((p/'EXECUTION_RECEIPT.json').read_text())
receipt['coefficient_structure_execution']={'actual_exit':0,'command':['python','coefficient_structure.py','--coefficients','native_tableau_bits.json','--out','coefficient_structure.json'],'stdout':'coefficient_structure.log','stderr':'coefficient_structure.stderr'}
receipt['native_dump_provenance']={'source':'../arithmetic/probe/src/bin/tableau_bits.rs','receipt':'../arithmetic/NATIVE_EXECUTION.json','actual_exit':0}
receipt['result_sha256']=hashlib.sha256((p/'results.json').read_bytes()).hexdigest()
(p/'EXECUTION_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n')
print('machine files written')
